// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD1yxRzamDsiM7yplll4r2fCt94QrUpdY',
    appId: '1:605162259067:web:059d296089d569193598de',
    messagingSenderId: '605162259067',
    projectId: 'unievents-8e58a',
    authDomain: 'unievents-8e58a.firebaseapp.com',
    storageBucket: 'unievents-8e58a.appspot.com',
    measurementId: 'G-PW74FFE77G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-4jpU0zTJSjbNAEgSIwmYYqg3sWrevBg',
    appId: '1:605162259067:android:d5bb13d0ee694d373598de',
    messagingSenderId: '605162259067',
    projectId: 'unievents-8e58a',
    storageBucket: 'unievents-8e58a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs2t6w0wsiPgGNKTR1s_ua0GEpf2Jh-oU',
    appId: '1:605162259067:ios:50abe2d09e630cf03598de',
    messagingSenderId: '605162259067',
    projectId: 'unievents-8e58a',
    storageBucket: 'unievents-8e58a.appspot.com',
    iosClientId: '605162259067-34csu3s6ujtsi4s5i3f0v3mt4fhnqurk.apps.googleusercontent.com',
    iosBundleId: 'com.fillip.uniEvents',
  );
}
